apiVersion: v1
description: A NATS Streaming cluster setup
name: nats-streaming-cluster
version: 0.2.0
appVersion: 0.6.0
keywords:
- NATS
- Messaging
- publish
- subscribe
- streaming
- cluster
- persistence
home: https://nats.io/
