# Default values for nats-streaming-server.

# NATS Streaming will use a StatefulSet for the follower replicas
# and then rely on a single Pod for bootstrapping.
replicaCount: 3

image:
  repository: nats-streaming
  tag: 0.9.2
  pullPolicy: IfNotPresent

#
# Streaming server configuration
#

# Cluster ID (default: test-cluster)
clusterID: "test-cluster"
  
# Connect to this external NATS Server URL
natsUrl: "nats://nats:4222"

# Max number of channels (0 for unlimited)
maxChannels: 100
  
# Max number of subscriptions per channel (0 for unlimited)
maxSubs: 1000

# Max number of messages per channel (0 for unlimited)
maxMsgs: "1000000"

# Max messages total size per channel (0 for unlimited)
maxBytes:  "900mb"

# Max duration a message can be stored ("0s" for unlimited)
maxAge: 0

#
# ADVANCED CONFIGURATION:  Change these with caution.
#

# Interval at which server sends heartbeat to a client
hbInterval: 30s

# How long server waits for a heartbeat response
hbTimeout: 10s

# Number of failed heartbeats before server closes the client connection
hbFailCount: 330

# Use for general debugging.  Enabling this will negatively affect performance.
debug: false

# Do not normally set this as it will drastically decrease performance and generate
# volumous logs.
trace: false

#
# The streaming service is for monitoring and liveness probes
#
service:
  name: nats-streaming-monitoring
  type: ClusterIP
  monitorPort: 8222

persistence:
  file:

    #  Enable compaction
    compactEnabled: true

    # Enable file CRC-32 checksum
    crc: true

    # Enable File.Sync on Flush
    sync: true

    # Store will try to use no more file descriptors than this given limit
    fdsLimit: 0

    ##
    ## ADVANCED CONFIGURATION:  Change these with caution.
    ## 
    # File buffer size (in bytes)
    bufferSize: "2097152"

    # File fragmentation % threshold for compaction
    compactFrag: 50

    # Minimum interval (in seconds) between file compactions, 5min
    compactInterval: 300

    #  Minimum file size for compaction
    compactMinSize: "1048576"

    # Polynomial used to make the table used for CRC-32 checksum (default is crc32.IEEE)
    crcPoly : "3988292384"

    # Maximum number of messages per file slice (subject to channel limits)
    sliceMaxMsgs: 0

    # Maximum file slice size - including index file (subject to channel limits)  64MB
    sliceMaxBytes: "67108931"

    # Maximum file slice duration starting when the first message is stored (subject to channel limits)
    sliceMaxAge: 0

    # Path to script to use if you want to archive a file slice being removed
    sliceArchiveScript: ""

    #  On startup, number of channels that can be recovered in parallel
    parallelRecovery: 1
 
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
