{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "nats-streaming-cluster.fullname" . }}
  labels:
    app: "{{ template "nats-streaming-cluster.name" . }}"
    chart: "{{ template "nats-streaming-cluster.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  podSelector:
    matchLabels:
      app: "{{ template "nats-streaming-cluster.name" . }}"
      release: {{ .Release.Name | quote }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: {{ .Values.monitoring.service.port }}
{{- end }}
